### ISSUE TITLE
fontMetrics bug

### ISSUE THREAD

**Issue by miminno** [jfree/jfreesvg#1]
The graphics object created from fmImage must have KEY_FRACTIONALMETRICS hint set to ON.
Without it the FontMetrics won't be able to properly measure text, i.e. the stringWidth(str) function will return an incorrect value.

**Comment by jfree** [comment]
Thanks for the feedback.  I committed this:

https://github.com/jfree/jfreesvg/commit/4f1f041d2c4884090dddf3c876091d9c241a3038
