### ISSUE TITLE
Ability to set absolute sizes (in mm) for the vector drawings

### ISSUE THREAD

**Issue by rkrishnasanka** [jfree/jfreesvg#11]
It would be great if all the geometries could be assigned absolute sizes. (Perhaps a mode switch that would let me define what the unit dimensions would be).

More information on why it seems to be a solution to get get SVGs of an absolute size

https://mpetroff.net/2013/08/analysis-of-svg-units/

**Comment by jfree** [comment]
From JFreeSVG 3.2 onwards you have the ability to set the units for the SVG and also the view box, which would seem to allow what is discussed in the link you provided.  In JFreeSVG 3.4 I will provide an option to change the font size units (which are currently hard coded to px).
