### ISSUE TITLE
Possible circular dependencies missing from JFreeChart 1.5

### ISSUE THREAD

**Issue by wltjr** [jfree/jfreesvg#12]
I was updating Gentoo ebuilds for jfree related packages. I ran into a problem with JFreeSVG 3.2. It seems to be using classes from an older version of JFreeChart that are not in JFreeChart 1.5.
```java
import org.jfree.chart.drawable.GradientPainter;
import org.jfree.chart.drawable.ColorPainter;
import org.jfree.chart.ChartUtilities;
```
Likely in a past version. Gentoo has JFreeChart 1.0.19 but that depends on JFreeSVG 2.1.x. I rather avoid the older versions. Not to mention the circular dependencies.

Could JFreeSVG be updated to newer JFreeChart?

Seems only a few classes are missing. If not I can see about using the existing Gentoo ebuilds. Just seems odd to have to have multiple older versions to build the latest. Need JFreeSVG 2.1.x for JFreeChart 1.0.19. Which in turn JFreeChart 1.0.19 is used by JFreeSVG 3.2. Need 2 older versions of each for the latest versions of each. Thanks!

**Comment by jfree** [comment]
JFreeSVG will be updated very soon, but note that the dependency on JFreeChart is only for the demo applications, not JFreeSVG itself.  I'll be moving the demos into jfree-demos project here at GitHub so that JFreeSVG won't contain any dependencies.

**Comment by wltjr** [comment]
Awesome, that sounds great! I noticed you were making some other changes. Figures I jumped the gun a bit. No worries, and good to know on demos. I can see about removing that for now. Not sure I will package that, once split into stand alone repo. Unless someone requests. Thank you very much!

Nice work otherwise! The newer versions already seem to have less dependencies than before.

**Comment by jfree** [comment]
JFreeSVG 3.3 is uploaded now, demos are transferred out.

**Comment by wltjr** [comment]
Excellent, though I had already taken care of 3.2 less the demos per your comment. Just went to fetch 3.3 and did not see it tagged/released in Github. I am using it as the source for the packages I am creating.

**Comment by jfree** [comment]
Oops...tagged the release just now.

**Comment by wltjr** [comment]
Thanks much!
