### ISSUE TITLE
opacity in gradients

### ISSUE THREAD

**Issue by miminno** [jfree/jfreesvg#2]
Currently opacity is not handled in gradients at all.
Svg linearGradient stop can either accept an rgba color, or have a stop-opacity style attribute, neither of which are present in the current code. The rgbaColorStr function exists but is not used,

**Comment by miminno** [comment]
Any feedback on this? Thx

**Comment by jfree** [comment]
I took a look at this and prepared a fix for the next release.  I'll dig that change out soon and commit it so you can take a look and give it a try.

**Comment by jfree** [comment]
This should fix it:

https://github.com/jfree/jfreesvg/commit/47777492373e59ca48e0f81b7ac91ec58b898353
