### ISSUE TITLE
SVG filter effects support

### ISSUE THREAD

**Issue by BuZZ-dEE** [jfree/jfreesvg#23]
Please add support for [SVG filters effects][0]. I would be great if SVG Salamander could render the [SVGram filter effects][1].

[0]: https://www.w3.org/TR/filter-effects-1/
[1]: https://github.com/BuZZ-dEE/SVGram

**Comment by jfree** [comment]
JFreeSVG is intended to support the features and approach defined by Java2D's Graphics2D API.  These filter effects go beyond that - I'm not sure how it could be implemented within JFreeSVG without stretching the library a little bit out of shape.
