### ISSUE TITLE
JFreeSVG 4.1 not in Maven Central

### ISSUE THREAD

**Issue by tomas-pluskal** [jfree/jfreesvg#31]
https://search.maven.org/search?q=jfreesvg

The latest version there is 3.4

**Comment by jfree** [comment]
That's the latest version available for Java 8.  There is a newer modular version available for Java 11 or later:

https://search.maven.org/artifact/org.jfree/org.jfree.svg

**Comment by tomas-pluskal** [comment]
Ah, I see, thanks!
