### ISSUE TITLE
What lib would you use to parse SVG files?

### ISSUE THREAD

**Issue by i-make-robots** [jfree/jfreesvg#51]
Hi!

I'm currently using Batik for parsing SVG files into our custom internal format.  it's got issues and the devs are well hidden.
If you were me, what library would you use instead?

Thanks!

**Comment by jfree** [comment]
I don't know to be honest.  Batik is the only Java library I'm aware of that parses and renders SVG.  JFreeSVG, as you've probably discovered, only generates SVG.
