### ISSUE TITLE
Avoid writing double semicolon in SVG style attribute

### ISSUE THREAD

**Issue by DaveJarvis** [jfree/jfreesvg#52]
When exporting a plot from Renjin as SVG, a double semicolon is written. For example:

```r
svg("/tmp/filename.svg");
plot(rnorm(5));
dev.off();
```

Renjin uses JFreeSVG, which produces:

```
<ellipse
  cx="61.5" cy="219.5" rx="2.5" ry="2.5"
  style="...snip... stroke-linecap: square;; fill: none" ...snip... />
```

Unfortunately, the ConTeXt typesetting engine has a bug that ignores styles after a null entry is detected in the style list, resulting in all such diagrams being rendered as a big black square (because the `fill:none` isn't honoured).

Any idea what's causing the `;;` to be generated?

ConTeXt (PDF) on the left and FlyingSaucer (XHTML) on the right:

![render-r-plot](https://user-images.githubusercontent.com/2131950/167489892-702f5bd1-5acd-4b43-a68f-c4c2602cbdc7.png)

FlyingSaucer handles `;;` fine, but not ConTeXt.

**Comment by jfree** [comment]
The double semi-colon is a bug that is fixed in the main branch (JFreeSVG 5.0.2) but that didn't get back-ported to the 3.4.x series yet.  I did that just now and pushed the changes, but I still have some more testing to do before I will release that.
