### ISSUE TITLE
Is there any mechanism within JFreeSvg to create a SvgGraphics2D instance from an SVG file/stream?

### ISSUE THREAD

**Issue by william-ferguson-au** [jfree/jfreesvg#7]

**Comment by jfree** [comment]
I presume you mean that you want to take some existing SVG and display it on the screen.  JFreeSVG doesn't do that, but Apache Batik does (maybe there are other libraries too, but I don't know).

**Comment by william-ferguson-au** [comment]
Thanks David. Yes I have already vetted Batik, but was looking for an alternative because it is so heavy weight.
